services:
  - type: web
    name: bot-whatsapp-hostel
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers=2 --worker-class=sync --timeout=30 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
